export const MovieQuotes = [
            { title: "Buzz Lightyear", response: "To infinity and beyond!" },
            { title: "Dory", response: "Just keep swimming." },
            { title: "Gandalf", response: "A wizard is never late, nor is he early. He arrives precisely when he means to." },
            { title: "Mufasa", response: "Remember who you are." },
            { title: "Forrest Gump", response: "Life is like a box of chocolates. You never know what you're gonna get." },
            { title: "Belle", response: "I want adventure in the great wide somewhere." },
            { title: "Yoda", response: "Do or do not. There is no try." },
            { title: "Albus Dumbledore", response: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light." },
            { title: "Elizabeth Swann", response: "You like pain? Try wearing a corset." },
            { title: "Harry Potter", response: "I solemnly swear that I am up to no good." },
            { title: "Shrek", response: "Ogres are like onions." },
            { title: "Dumbledore", response: "It does not do to dwell on dreams and forget to live." },
            { title: "Leia Organa", response: "Help me, Obi-Wan Kenobi. You're my only hope." },
            { title: "Simba", response: "Hakuna Matata! What a wonderful phrase." },
            { title: "Jack Sparrow", response: "Why is the rum always gone?" },
            { title: "Indiana Jones", response: "I’ve got a bad feeling about this." },
            { title: "Alice", response: "We're all mad here." },
            { title: "Willy Wonka", response: "We are the music makers, and we are the dreamers of dreams." },
            { title: "Ellie", response: "Adventure is out there!" },
            { title: "Merida", response: "I’ll be shooting for my own hand." },
            { title: "Wall-E", response: "Wall-E! Wall-E!" },
            { title: "Lightning McQueen", response: "Ka-Chow!" },
            { title: "Velma Dinkley", response: "Jinkies!" },
            { title: "Ray", response: "Dig a little deeper." },
            { title: "Bambi", response: "If you can’t say something nice, don’t say anything at all." },
            { title: "E.T.", response: "E.T. phone home." },
            { title: "Marlin", response: "Just keep swimming." },
            { title: "Puss in Boots", response: "Let’s rock." },
            { title: "Lilo", response: "Ohana means family, and family means nobody gets left behind." },
            { title: "Mr. Incredible", response: "I’m Mr. Incredible!" },
            { title: "Ray", response: "Your focus determines your reality." },
            { title: "Pocahontas", response: "The earth is my home." },
            { title: "Alice", response: "We’re all mad here." },
            { title: "Thor", response: "I am not a king or a monster. I am more." },
            { title: "Marlin", response: "I promise I’ll never let anything happen to you." },
            { title: "Anna", response: "The sky’s awake, so I’m awake." },
            { title: "Simba", response: "Remember who you are." },
            { title: "Olaf", response: "I’m a little cold, but I like warm hugs!" },
            { title: "Pumbaa", response: "Hakuna Matata! What a wonderful phrase." },
            { title: "Edna Mode", response: "No capes!" },
            { title: "Mickey Mouse", response: "Oh, boy!" },
            { title: "Percy Jackson", response: "You shouldn’t have opened that door." },
            { title: "Merida", response: "I’m not a princess. I’m a warrior." },
            { title: "Buzz Lightyear", response: "You are a sad, strange little man." },
            { title: "Lilo", response: "Ohana means family." },
            { title: "Rapunzel", response: "You’re my new dream." },
            { title: "Mulan", response: "The flower that blooms in adversity is the most rare and beautiful of all." },
    ]
export const Scriptures = [
            { title: "John 3:16", response: "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life." },
            { title: "Psalm 23:4", response: "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me." },
            { title: "Isaiah 40:31", response: "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint." },
            { title: "Proverbs 3:5-6", response: "Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths." },
            { title: "Ecclesiastes 3:1", response: "For everything there is a season, and a time for every matter under heaven." },
            { title: "Jeremiah 29:11", response: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope." },
            { title: "Matthew 6:34", response: "Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble." },
            { title: "Romans 8:28", response: "And we know that for those who love God all things work together for good, for those who are called according to his purpose." },
            { title: "1 Corinthians 13:4-7", response: "Love is patient and kind; love does not envy or boast; it is not arrogant or rude. Love does not insist on its own way; it is not irritable or resentful; it does not rejoice at wrongdoing, but rejoices with the truth. Love bears all things, believes all things, hopes all things, endures all things." },
            { title: "Psalm 46:1", response: "God is our refuge and strength, a very present help in trouble." },
            { title: "Proverbs 16:3", response: "Commit your work to the Lord, and your plans will be established." },
            { title: "Philippians 4:13", response: "I can do all things through him who strengthens me." },
            { title: "Hebrews 11:1", response: "Now faith is the assurance of things hoped for, the conviction of things not seen." },
            { title: "Psalm 34:18", response: "The Lord is near to the brokenhearted and saves the crushed in spirit." },
            { title: "2 Corinthians 5:7", response: "For we walk by faith, not by sight." },
            { title: "Isaiah 41:10", response: "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand." },
            { title: "Revelation 21:4", response: "He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away." },
            { title: "James 1:2-4", response: "Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness." },
            { title: "Deuteronomy 31:8", response: "It is the Lord who goes before you. He will be with you; he will not leave you or forsake you. Do not fear or be dismayed." },
            { title: "Titus 3:5", response: "He saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit." },
            { title: "Psalm 18:2", response: "The Lord is my rock and my fortress and my deliverer, my God, my rock, in whom I take refuge, my shield, and the horn of my salvation, my stronghold." },
            { title: "John 14:6", response: "Jesus said to him, 'I am the way, and the truth, and the life. No one comes to the Father except through me.'" },
            { title: "Ephesians 2:8-9", response: "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast." },
            { title: "Colossians 3:23-24", response: "Whatever you do, work heartily, as for the Lord and not for men, knowing that from the Lord you will receive the inheritance as your reward. You are serving the Lord Christ." },
            { title: "1 John 4:8", response: "Anyone who does not love does not know God, because God is love." },
            { title: "Matthew 7:7-8", response: "Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you. For everyone who asks receives, and the one who seeks finds, and to the one who knocks it will be opened." },
            { title: "Psalm 147:3", response: "He heals the brokenhearted and binds up their wounds." },
            { title: "Proverbs 10:22", response: "The blessing of the Lord makes rich, and he adds no sorrow with it." },
            { title: "Lamentations 3:22-23", response: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness." },
            { title: "Isaiah 55:8-9", response: "For my thoughts are not your thoughts, neither are your ways my ways, declares the Lord. For as the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts." },
            { title: "Romans 5:8", response: "But God shows his love for us in that while we were still sinners, Christ died for us." },
            { title: "Psalm 103:12", response: "As far as the east is from the west, so far does he remove our transgressions from us." },
            { title: "Proverbs 15:1", response: "A soft answer turns away wrath, but a harsh word stirs up anger." },
            { title: "Ecclesiastes 12:13", response: "The end of the matter; all has been heard. Fear God and keep his commandments, for this is the whole duty of man." },
            { title: "John 8:32", response: "And you will know the truth, and the truth will set you free." },
            { title: "Galatians 6:9", response: "Let us not grow weary of doing good, for in due season we will reap, if we do not give up." },
            { title: "Philippians 1:6", response: "And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ." },
            { title: "2 Timothy 1:7", response: "For God gave us a spirit not of fear but of power and love and self-control." },
            { title: "Psalm 119:105", response: "Your word is a lamp to my feet and a light to my path." },
            { title: "Matthew 22:37-38", response: "And he said to him, 'You shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the great and first commandment.'" },
            { title: "Titus 2:11", response: "For the grace of God has appeared, bringing salvation for all people." },
            { title: "1 Peter 5:7", response: "Casting all your anxieties on him, because he cares for you." },
            { title: "Proverbs 12:25", response: "Anxiety in a man's heart weighs him down, but a good word makes him glad." },
            { title: "Revelation 3:20", response: "Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me." },
            { title: "James 4:8", response: "Draw near to God, and he will draw near to you." },
            { title: "Matthew 28:18-20", response: "And Jesus came and said to them, 'All authority in heaven and on earth has been given to me. Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all that I have commanded you. And behold, I am with you always, to the end of the age.'" },
            { title: "Psalm 84:11", response: "For the Lord God is a sun and shield; the Lord bestows favor and honor. No good thing does he withhold from those who walk uprightly." },
            { title: "2 Peter 3:9", response: "The Lord is not slow to fulfill his promise as some count slowness, but is patient toward you, not wishing that any should perish, but that all should reach repentance." },
            { title: "John 14:27", response: "Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid." },
            { title: "Psalm 55:22", response: "Cast your burden on the Lord, and he will sustain you; he will never permit the righteous to be moved." },
            { title: "1 Thessalonians 5:16-18", response: "Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you." },
            { title: "Proverbs 18:10", response: "The name of the Lord is a strong tower; the righteous man runs into it and is safe." },
            { title: "2 Corinthians 12:9", response: "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.' Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me." },
            { title: "President Gordon B. Hinckley", response: "If we keep the commandments of God, we shall have power to resist evil and to enjoy that peace and serenity which comes from keeping the commandments." },
            { title: "President Ezra Taft Benson", response: "The faithful in Israel, holding on to the rod, find light, guidance, and protection." },
            { title: "President Brigham Young", response: "The gospel of Jesus Christ is a plan of happiness." },
            { title: "President Joseph Smith", response: "God will yet reveal many great and important things pertaining to the kingdom of God." },
            { title: "President Russell M. Nelson", response: "We are led by prophets of God who guide us in a perilous world. Their messages are full of hope." },
            { title: "President Howard W. Hunter", response: "God loves all His children, and He provides a way for them to be happy." },
            { title: "President Spencer W. Kimball", response: "We are not left to struggle alone. The Savior will help us bear our burdens." },
            { title: "President Thomas S. Monson", response: "To love and be loved is to feel the sun from both sides." },
            { title: "President James E. Faust", response: "We find ourselves most whole, most happy, and most satisfied when we place our trust in God." },
            { title: "President Dieter F. Uchtdorf", response: "It is not our abilities that show what we truly are, it is our choices." },
            { title: "President Gordon B. Hinckley", response: "Success is measured in terms of service and sacrifice." },
            { title: "President M. Russell Ballard", response: "Faith, prayer, repentance, forgiveness, respect, love, compassion, work, and family are the things that matter most." },
            { title: "President Wilford Woodruff", response: "The best way to prepare to meet God is to keep His commandments." },
            { title: "President Joseph Fielding Smith", response: "Righteousness exalts a nation, but sin is a reproach to any people." },
            { title: "President Boyd K. Packer", response: "God is anxious to help you, but you must do your part." },
            { title: "President Harold B. Lee", response: "Faithful living is the best insurance against the turbulent times in which we live." },
            { title: "President Russell M. Nelson", response: "Jesus Christ is the source of our hope, our peace, our strength, and our joy." },
            { title: "President Ezra Taft Benson", response: "The church is not an organization but a living body, organized for eternal purposes." },
            { title: "President Brigham Young", response: "The Lord is bound when we do what He says." },
            { title: "President Thomas S. Monson", response: "May the Lord bless you, and may you always walk in His light." },
            { title: "President Gordon B. Hinckley", response: "I am satisfied that no unhallowed hand can stop the work from progressing." },
            { title: "President Joseph Smith", response: "God is in the details. He wants to be involved in every aspect of our lives." },
            { title: "President Wilford Woodruff", response: "The gospel of Jesus Christ will go forth boldly and nobly." },
            { title: "President Spencer W. Kimball", response: "Obedience brings blessings; exact obedience brings miracles." },
            { title: "President Harold B. Lee", response: "The mission of the Church is to invite all to come unto Christ." },
            { title: "President Ezra Taft Benson", response: "Pride is a sin that blinds us." },
            { title: "President Gordon B. Hinckley", response: "The future is as bright as your faith." },
            { title: "President Thomas S. Monson", response: "Remember the faith of your ancestors and know that you are part of a marvelous latter-day work." },
            { title: "President Joseph Fielding Smith", response: "The greatest of all the gifts of God is the gift of eternal life." },
            { title: "President Boyd K. Packer", response: "The Lord requires each of us to be a witness of Him." },
            { title: "President Russell M. Nelson", response: "Every day, we are given choices—make them carefully, wisely, and in faith." },
            { title: "President Spencer W. Kimball", response: "It is only through humility and prayer that we can overcome our weaknesses." },
            { title: "President Harold B. Lee", response: "Live in such a way that your life is worth remembering." },
            { title: "President Ezra Taft Benson", response: "The home is the first great institution of learning." },
            { title: "President Brigham Young", response: "Obedience is the first law of heaven." },
            { title: "President Thomas S. Monson", response: "There is safety in righteous living." },
            { title: "President Gordon B. Hinckley", response: "Trust in the Lord and move forward with faith." },
            { title: "President Boyd K. Packer", response: "Righteous living is not a burden; it is the key to joy and happiness." },
            { title: "President Russell M. Nelson", response: "Now is the time to prepare. Prepare for what lies ahead." },
            { title: "President Joseph Smith", response: "Faith is not only an ideal but a principle of action." },
            { title: "President Brigham Young", response: "The gospel of Jesus Christ is a gospel of action." },
            { title: "President Thomas S. Monson", response: "Choose the harder right instead of the easier wrong." },
            { title: "President Ezra Taft Benson", response: "The Book of Mormon is the keystone of our religion." },
            { title: "President Joseph Fielding Smith", response: "To do good to others and to live a life of usefulness is to follow the path to eternal life." },
            { title: "President Gordon B. Hinckley", response: "Seek after truth, and the Lord will direct your paths." },
            { title: "President Russell M. Nelson", response: "Seek Him with all your heart. The Savior lives, and He stands at the door of your life, ready to come in." },
            { title: "President Boyd K. Packer", response: "The Lord expects us to live righteously." },
            { title: "President Thomas S. Monson", response: "We can do better, we must do better." },
            { title: "President Harold B. Lee", response: "The Lord will not be mocked." },
            { title: "President Spencer W. Kimball", response: "The time to be happy is now. The place to be happy is here." },
            { title: "President Ezra Taft Benson", response: "The Lord will never forsake those who are determined to keep His commandments." },
]